apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 10
  metric:
  - type: External
    custom:
      metric:
        name: custom.googleapis.com|rabbitmq_queue_messages
      target:
        type: AverageValue
        averageValue: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app