apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app
  namespace: default
spec:
  maxReplicas: 3
  metrics:
  - external:
      metric:
        name: custom.googleapis.com|rabbitmq_queue_messages
        selector: {}
      target:
        type: Value
        value: "10"
    type: External
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app